name:                trypurescript-lambda
version:             0.1.0
github:              "githubuser/trypurescript-lambda"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/trypurescript-lambda#readme>

dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime >= 3.0.0
- aeson
- purescript >= 0.14.5
- purescript-cst == 0.4.0.0
- language-javascript == 0.7.0.0
# ms add
- safe-exceptions-checked == 0.1.0
- time == 1.9.3
- text == 1.2.4.1
- containers >= 0.6.5
- data-default == 0.7.1.1
- bytestring == 0.10.12.0
- mtl == 2.2.2
- transformers == 0.5.6.2
- Glob == 0.10.1
- filepath == 1.4.2.1
- logging == 3.0.5
- template-haskell == 2.16.0.0
- lift-generics == 0.2.1
library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - trypurescript-lambda

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
