resolver: lts-16.31

packages:
- .

extra-deps:
- git: https://github.com/dnikolovv/aws-lambda-haskell-runtime.git
  commit: 3a9d26dee8a39fdbe7bd26bc0ec058f904cdf828
- purescript-0.14.5
- purescript-cst-0.4.0.0
- language-javascript-0.7.0.0

# copied from trypurescript
# no idea what these do...
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false